name: AccountSecurity
version: 0.1
author: DeprecatedNether
main: pw.deprecatednether.security.AccountSecurity
commands:
  accountsecurity:
    description: Base AccountSecurity command
    aliases: [as, asecurity]
permissions: